### ISSUE TITLE
Complete Font Failure on Safari

### ISSUE THREAD

**Issue by dwighthouse** [bramstein/fontfaceobserver#35]
I'm redesigning my website for mach speed. One of the changes is to have readable text asap, hence your library and following Filament Group's style of switching custom fonts on globally once they are detected as parsed: https://www.filamentgroup.com/lab/font-events.html

I have not yet implemented the server side rewrite to set the html class name fontsLoaded upon the detection of a cookie, I'm just at the point of showing the fallback and then jumping to the custom font when ready.

On Safari (OS X Yosemite 10.10.5, Safari Version 8.0.8), with empty cache or not, run as local or from a remote server, I'm getting full font failure in several distinct ways while using the fontfaceobserver library. I have also observed these effects on Safari for iOS (v9, I believe).

## Behavior Types
I enumerate the different kinds of weird behavior here first. Please note that in spite of all these behaviors, the Safari Inspector correctly reports style values, and a console log statement ensures that fontfaceobserver is actually running.

* Font Disappears - The place where the custom font (or even the fallback font) should display is simply invisible; areas that show the custom font when hovered have their text cut off
* Fallback Displayed - The place where the custom font should display (after having loaded) still shows the fallback font; areas that show the custom font when hovered have their text cut off
* Correct Behavior - Fallback font is displayed, but quickly replaced with the custom font (as soon as it is detected as loaded by fontfaceobserver)
* Immediate Custom Display - The custom font displays immediately, without showing the fallback font, even for a moment

## Scenarios
There are several different ways of interacting with the loading of the browser and fonts.

* When first loading the page, I have observed three types of behavior: Font Disappears, Fallback Displayed, and Correct Behavior.
* When going up to the address bar, highlighting the url, and pressing enter, I always get Correct Behavior.
* When reloading the page with keyboard shortcuts or the reload button in the address bar, I always get Fallback Displayed behavior.
* In the Font Disappears and Fallback Displayed behavior situations, if I resize the page in any way, the correct custom font appears.
* When the custom font is being displayed, if I leave for another website, returning via the back button results in Immediate Custom Display behavior.
* In the Fallback Displayed behavior situation, if I leave for another website, returning via the back button results in Font Disappears behavior (usually).
* In the Font Disappears behavior situation, if I leave for another website, returning via the back button results in Font Disappears behavior.
* In the Font Disappears behavior situation, if I reload the page, I always get Fallback Displayed behavior.

I've also seen one case where reloading caused a flash of the fallback font followed by the fonts disappearing. I've had other slight differences throughout my testing. Basically, few of the above are very consistent. I suspect some kind of race condition is going on in Safari.

## My Code
This is the abbreviated code relevant to the problem. Note that I have already tried without the src: local hack, with and without using quotes around my font url references, and tried both font-weight normal and font-weight 300. The font family name should be unique here (doesn't match any font names on my system). I have also tried explicitly setting the non-loaded styles to a font-family of sans-serif.

*CSS*
```css
@font-face {
    font-family: 'comfortaa-thin-custom';
    src: url(theme/fonts/comfortaa-thin.eot);
    src: local('☺︎'),
         url(theme/fonts/comfortaa-thin.eot?#iefix) format('embedded-opentype'),
         url(theme/fonts/comfortaa-thin.woff2) format('woff2'),
         url(theme/fonts/comfortaa-thin.woff) format('woff'),
         url(theme/fonts/comfortaa-thin.ttf) format('truetype'),
         url(theme/fonts/comfortaa-thin.svg#comfortaathin) format('svg');
    font-weight: 300;
    font-style: normal;
}

html, body {
    background: #ddd;
    font-family: sans-serif;
    color: #777;
}

.fontsLoaded .mainTitle, .fontsLoaded .sectionTitle, .fontsLoaded .imageText {
    font-family: 'comfortaa-thin-custom', sans-serif;
}

.mainTitle, .sectionTitle, .imageText {
    font-weight: 300;
}
```

*Javascript*
```javascript
(function(w) {
    (new w.FontFaceObserver('comfortaa-thin-custom')).check(null, 5000).then(function () {
        w.document.documentElement.className += " fontsLoaded";
        console.log('set font');
    }, function () {});
}(this));
```

I know this is somehow related to fontfaceobserver, because I tried replacing the fontfaceobserver activator code above with the following code, and got the expected behavior:

```javascript
setTimeout(function() {
    w.document.documentElement.className += " fontsLoaded";
}, 200);
```

In the above, it doesn't matter how short or long the timeout delay is, I still get the correct behavior (eventually), albeit with the flash of invisible text due to the time to load/parse the font. Also, when arriving at the page using the back button it loads the font immediately, probably not actually reloading the page, but from a cache of the existing page's contents.

Setting the styles to use the custom font in the CSS immediately (without JS), I get the standard flash of invisible text until the font is loaded.

## Examples
Here is a version of my website that exhibits this behavior: http://exp.dwighthouse.com/hex/
Here is a video of the problem: http://exp.dwighthouse.com/FontFailureSafari/FontLoadFailureOnSafari.mov
